#!/usr/bin/env bash

set -e

JTOOLS_FOLDER=${JTOOLS_FOLDER:=$HOME/.jtools}
JTOOLS_BINS_FOLDER="$JTOOLS_FOLDER/bins"

create_jtools_folders_if_necessary() {
	if [ ! -d $JTOOLS_BINS_FOLDER ]; then
		mkdir -p "$JTOOLS_BINS_FOLDER"
	fi
}

check_folder_not_exists() {
	name="$1"
	path="$2"
	if [ -e $path ]; then
		echo "$name already installed or install folder $path already exists, exiting."
		exit 1
	fi
}

yes_or_no() {
	read -p "$1" choice
	case "$choice" in
		y|Y) echo "yes";;
	  *) echo "no";;
	esac
}

create_symlink() {
	program_path="$1"
	program_name="$2"
	ln -s "$program_path" "$JTOOLS_BINS_FOLDER/$program_name"
}

remove_symlink() {
	program="$1"
	rm -f "$JTOOLS_BINS_FOLDER/$program"
}

select_dl_tool() {
	if hash wget 2>/dev/null; then
		# wget exists
		echo "wget -q -O-"
	else 
		if hash curl 2>/dev/null; then
			# curl exists
			echo "curl"
		else
			if hash http 2>/dev/null; then
				# httpie exists
				echo "http GET"
			else
				echo "Could not find either wget, curl or httpie, exiting."
				exit 1
			fi
		fi
	fi
}

extract_links() {
	url="$1"
	dl_tool=$(select_dl_tool)
	$dl_tool $url | awk 'BEGIN{
RS="</a>"
IGNORECASE=1
}
{
  for(o=1;o<=NF;o++){
    if ( $o ~ /href/){
      gsub(/.*href=\042/,"",$o)
      gsub(/\042.*/,"",$o)
      print $(o)
    }
  }
}'
}