#!/usr/bin/env bash

set -e

# Provide jtools completions
if [ "$1" = "--complete" ]; then
	echo install
	echo remove
fi

base_install_path=${JTOOLS_INSTALL_PATH:=~/.bin}
full_install_path=$base_install_path/_sbt
symlink_to_parent=${JTOOLS_SYMLINK_TO_PARENT:=true}

install_sbt() {
	echo "Installing SBT..."

	if [ -e $full_install_path ]; then
		echo "SBT already installed or install folder $full_install_path already exists, exiting."
		exit 1
	fi

	git clone git@github.com:paulp/sbt-extras $full_install_path 2>/dev/null

	echo "SBT successfully installed to $full_install_path"
	if [ "$symlink_to_parent" = "true" ]; then
		echo "Symlinking $full_install_path/sbt to $base_install_path/sbt..."
		ln -s $full_install_path/sbt $base_install_path/sbt
	fi
}

remove_sbt() {
	result=$(yes_or_no "Are you sure you want to remove SBT ? [y/n] ")
	case "$result" in
		yes)
			rm -Rf $full_install_path
			echo "SBT successfully removed."
			if [ "$symlink_to_parent" = "true" ]; then
				rm $base_install_path/sbt
				echo "Symlink successfully removed."
			fi
			;;
		*) ;;
	esac
}

yes_or_no() {
	read -p "$1" choice
	case "$choice" in
		y|Y) echo "yes";;
	  *) echo "no";;
	esac
}

case "$1" in
	install) 
		install_sbt;;
	remove)
		remove_sbt;;
esac

